/*
 * Copyright 1997-2026 Optimatika
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.ojalgo.optimisation.integer;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.Map.Entry;
import java.util.concurrent.atomic.AtomicInteger;

import org.ojalgo.ProgrammingError;
import org.ojalgo.equation.Equation;
import org.ojalgo.function.constant.BigMath;
import org.ojalgo.function.special.MissingMath;
import org.ojalgo.netio.BasicLogger;
import org.ojalgo.optimisation.Expression;
import org.ojalgo.optimisation.ExpressionsBasedModel;
import org.ojalgo.optimisation.IntermediateSolver;
import org.ojalgo.optimisation.ModelEntity;
import org.ojalgo.optimisation.UpdatableSolver;
import org.ojalgo.optimisation.Variable;
import org.ojalgo.optimisation.integer.IntegerStrategy.CutConfiguration;
import org.ojalgo.structure.Structure1D.IntIndex;
import org.ojalgo.type.TypeUtils;
import org.ojalgo.type.context.NumberContext;
import org.ojalgo.type.keyvalue.EntryPair;
import org.ojalgo.type.keyvalue.EntryPair.KeyedPrimitive;

public final class NodeSolver extends IntermediateSolver {

    abstract static class Separator {

    }

    private static final NumberContext COEFFICIENT = NumberContext.of(12).withMode(RoundingMode.CEILING);
    private static final AtomicInteger COUNTER = new AtomicInteger();
    private static final boolean DEBUG = false;
    private static final BigDecimal EPS_RELAX_ABS = new BigDecimal("1E-11");
    private static final BigDecimal EPS_RELAX_REL = new BigDecimal("1E-13");
    private static final NumberContext LIMIT = NumberContext.of(12).withMode(RoundingMode.FLOOR);
    private static final NumberContext PARAMETERS = NumberContext.of(12);
    private static final NumberContext PRECISION = NumberContext.of(12);
    private static final NumberContext SCALE = NumberContext.of(14);

    /**
     * Cached result of {@link ExpressionsBasedModel.EntityMap#integers(ExpressionsBasedModel)}, paired with
     * the {@link ExpressionsBasedModel.EntityMap} instance it was computed from. The flags only change when
     * the underlying solver (and therefore its entityMap) is regenerated by {@link IntermediateSolver}; we
     * detect that by reference identity and recompute lazily.
     */
    private boolean[] myCachedIntegers = null;
    private ExpressionsBasedModel.EntityMap myCachedIntegersFor = null;
    private boolean myCutRoundDone = false;
    private FlowCoverSeparator myFlowCoverSeparator = null;
    private Boolean myInPlaceBoundUpdateSafe = null;
    private MIRSeparator myMIRSeparator = null;

    NodeSolver(final ExpressionsBasedModel model) {
        super(model);
    }

    private boolean doGenerateFlowCoverCuts(final IntegerStrategy.CutConfiguration configuration, final ExpressionsBasedModel target) {

        if (!this.isSolved()) {
            return false;
        }

        Result result = this.getResult();

        long nbConstr = target.constraints().count();

        if (myFlowCoverSeparator == null) {
            myFlowCoverSeparator = new FlowCoverSeparator(this.getModel());
        }
        myFlowCoverSeparator.generateCuts(result, target);

        return nbConstr != target.constraints().count();
    }

    private boolean doGenerateGMICuts(final IntegerStrategy.CutConfiguration configuration, final ExpressionsBasedModel target) {

        if (!this.isSolved()) {
            return false;
        }

        ExpressionsBasedModel model = this.getModel();
        Solver solver = this.getSolver();
        Result result = this.getResult();

        long nbConstr = target.constraints().count();

        if (model.countVariables() != target.countVariables()) {
            throw new IllegalStateException();
        }

        if (solver instanceof UpdatableSolver) {
            UpdatableSolver updatable = (UpdatableSolver) solver;

            ExpressionsBasedModel.EntityMap entityMap = updatable.getEntityMap().orElseThrow(ProgrammingError::new);

            if (entityMap != null) {

                int nbProblVars = entityMap.countModelVariables();
                int nbSlackVars = entityMap.countSlackVariables();

                boolean[] integers;
                if (myCachedIntegersFor == entityMap && myCachedIntegers != null) {
                    integers = myCachedIntegers;
                } else {
                    integers = entityMap.integers(model);
                    myCachedIntegers = integers;
                    myCachedIntegersFor = entityMap;
                }

                Collection<Equation> potentialCuts = updatable.generateCutCandidates(integers, configuration);

                int maxCuts = configuration.getMaxCuts(nbProblVars);
                int maxElements = configuration.getMaxElements(nbProblVars);

                List<KeyedPrimitive<String>> acceptedEfficacies = new ArrayList<>();

                for (Equation equation : potentialCuts) {

                    String name = "CUT_GMI_" + equation.index + "_" + COUNTER.incrementAndGet();

                    if (DEBUG) {
                        BasicLogger.debug();
                        BasicLogger.debug("Equat: {} {}", name, equation.toString());
                        BasicLogger.debug();
                    }

                    Expression cut = target.newExpression(name);

                    cut.lower(BigDecimal.valueOf(equation.getRHS()));

                    for (int j = 0; j < nbProblVars; j++) {
                        double aj = equation.doubleValue(j);
                        if (!SCALE.isZero(aj)) {

                            int mj = entityMap.indexOf(j);

                            BigDecimal AJ = TypeUtils.toBigDecimal(aj, SCALE);
                            if (entityMap.isNegated(j)) {
                                cut.add(mj, AJ.negate());
                            } else {
                                cut.add(mj, AJ);
                            }

                            if (DEBUG) {
                                BasicLogger.debug("Var   {} =->> Cut {}: {} < {}", target.getVariable(mj), name, cut.getLowerLimit(), cut.getLinearEntrySet());
                            }
                        }
                    }

                    for (int j = 0; j < nbSlackVars; j++) {
                        double aj = equation.doubleValue(nbProblVars + j);
                        if (!SCALE.isZero(aj)) {

                            EntryPair<ModelEntity<?>, ConstraintType> pair = entityMap.getSlack(j);

                            ModelEntity<?> entity = pair.getKey();
                            ConstraintType type = pair.getValue();
                            BigDecimal coefficient = TypeUtils.toBigDecimal(aj, SCALE);
                            BigDecimal adjusted = entity.adjust(coefficient);

                            if (ConstraintType.LOWER.equals(type)) {

                                BigDecimal factor = adjusted;
                                BigDecimal limit = entity.getLowerLimit();

                                BigDecimal shift = limit.multiply(factor);
                                cut.shift(shift);

                                entity.addTo(cut, factor);
                            }

                            if (ConstraintType.UPPER.equals(type)) {

                                BigDecimal factor = adjusted.negate();
                                BigDecimal limit = entity.getUpperLimit();

                                BigDecimal shift = limit.multiply(factor);
                                cut.shift(shift);

                                entity.addTo(cut, factor);
                            }

                            if (DEBUG) {
                                BasicLogger.debug("Slack {} {} =->> Cut {}: {} < {}", type, entity, name, cut.getLowerLimit(), cut.getLinearEntrySet());
                            }
                        }
                    }

                    BigDecimal cRHS = cut.getLowerLimit();

                    BigDecimal violation = configuration.violation;
                    if (cRHS.abs().compareTo(violation) > 0) {
                        target.removeExpression(name);
                        if (DEBUG) {
                            BasicLogger.debug(1, "Violation small! {}", cRHS);
                        }
                        continue;
                    }

                    BigDecimal cLargest = BigMath.ONE;
                    for (Entry<IntIndex, BigDecimal> entry : cut.getLinearEntrySet()) {
                        cLargest = cLargest.max(entry.getValue().abs());
                    }

                    boolean discardCut = false;
                    BigDecimal cSmallest = BigMath.VERY_POSITIVE;
                    for (Iterator<Entry<IntIndex, BigDecimal>> iterator = cut.getLinearEntrySet().iterator(); iterator.hasNext();) {
                        Entry<IntIndex, BigDecimal> entry = iterator.next();

                        BigDecimal cValue = entry.getValue();

                        if (!PRECISION.isSmall(cLargest, cValue)) {
                            cSmallest = cSmallest.min(cValue.abs());
                            entry.setValue(COEFFICIENT.enforce(cValue));
                        } else {
                            Variable var = model.getVariable(entry.getKey().index);
                            BigDecimal bound = cValue.signum() > 0 ? var.getUpperLimit() : var.getLowerLimit();
                            if (bound == null) {
                                discardCut = true;
                                break;
                            }
                            cRHS = cRHS.subtract(cValue.multiply(bound));
                            iterator.remove();
                        }
                    }

                    if (discardCut) {
                        target.removeExpression(name);
                        continue;
                    }

                    cRHS = LIMIT.enforce(cRHS);
                    cRHS = cRHS.subtract(cRHS.abs().multiply(EPS_RELAX_REL).add(EPS_RELAX_ABS));
                    cut.lower(cRHS);

                    BigDecimal cEvaluated = cut.evaluate(result);
                    BigDecimal cDiff = cRHS.subtract(cEvaluated);

                    if (DEBUG) {
                        BigDecimal cRatio = MissingMath.divide(cLargest, cSmallest);
                        BigDecimal cEfficacy = MissingMath.divide(cDiff, cLargest);
                        BasicLogger.debug(1, "Largest={}, Smallest={}, Ratio={}, RHS={}, Evaluated={},  Difference={}", cLargest, cSmallest, cRatio, cRHS,
                                cEvaluated, cDiff);
                    }

                    if (cDiff.signum() <= 0 || configuration.efficacy.isSmall(cLargest, cDiff)) {
                        target.removeExpression(name);
                        if (DEBUG) {
                            BasicLogger.debug(1, "Efficacy small! {} << {}", cDiff, cLargest);
                        }

                    } else if (configuration.dynanism.isSmall(cLargest, cSmallest)) {
                        target.removeExpression(name);
                        if (DEBUG) {
                            BasicLogger.debug(1, "Dynanism large! {} >> {}", cLargest, cSmallest);
                        }

                    } else if (cut.getLinearEntrySet().size() > maxElements) {
                        target.removeExpression(name);
                        if (DEBUG) {
                            BasicLogger.debug(1, "Too dense! {} > {}", cut.getLinearEntrySet().size(), maxElements);
                        }

                    } else if (target.checkSimilarity(cut)) {
                        target.removeExpression(name);
                        if (DEBUG) {
                            BasicLogger.debug(1, "Cut similar to current constraint!");
                        }

                    } else {

                        cut.enforce(PARAMETERS);
                        cut.tighten();

                        double normalizedEfficacy = cDiff.doubleValue() / cLargest.doubleValue();

                        acceptedEfficacies.add(EntryPair.of(name, normalizedEfficacy));

                        if (DEBUG) {
                            BasicLogger.debug(1, "{}", cut);
                            BasicLogger.debug(1, "{} < {}", cut.getLowerLimit(), cut.getLinearEntrySet());
                        }

                        if (target.options.logger_detailed && target.options.logger_appender != null) {
                            target.options.logger_appender.println("{}: {} < {}", name, cut.getLowerLimit(), cut.getLinearEntrySet());
                        }
                    }
                }

                if (acceptedEfficacies.size() > maxCuts) {

                    acceptedEfficacies.sort(Comparator.comparingDouble(KeyedPrimitive::doubleValue));
                    for (int i = 0, limit = acceptedEfficacies.size() - maxCuts; i < limit; i++) {
                        target.removeExpression(acceptedEfficacies.get(i).getKey());
                    }
                }
            }
        }

        return nbConstr != target.constraints().count();
    }

    private boolean doGenerateMIRCuts(final IntegerStrategy.CutConfiguration configuration, final ExpressionsBasedModel target) {

        if (!this.isSolved()) {
            return false;
        }

        Result result = this.getResult();

        if (myMIRSeparator == null) {
            myMIRSeparator = new MIRSeparator(this.getModel());
        }

        return myMIRSeparator.generateCuts(result, target, configuration);
    }

    private boolean generateCuts(final ExpressionsBasedModel target, final CutConfiguration configGMI, final CutConfiguration configMIR,
            final CutConfiguration configFC) {

        int roundsFC = configFC != null ? configFC.iterations : 0;
        int roundsMIR = configMIR != null ? configMIR.iterations : 0;
        int roundsGMI = configGMI != null ? configGMI.iterations : 0;

        int maxRounds = MissingMath.max(roundsFC, roundsMIR, roundsGMI);

        boolean retVal = false;

        for (int round = 0; round < maxRounds; round++) {

            boolean added = false;

            if (round < roundsFC) {
                added |= this.doGenerateFlowCoverCuts(configFC, target);
            }

            if (round < roundsMIR) {
                added |= this.doGenerateMIRCuts(configMIR, target);
            }

            if (round < roundsGMI) {
                added |= this.doGenerateGMICuts(configGMI, target);
            }

            if (added) {

                retVal |= added;

                this.reset();
                Result result = this.getResult();

                if (result == null || !result.getState().isOptimal()) {
                    break;
                }

            } else {

                break;
            }
        }

        return retVal;
    }

    boolean generateCuts(final ModelStrategy strategy) {

        if (this.generateCuts(this.getModel(), strategy.getGMICutConfiguration(), strategy.getMIRCutConfiguration(), strategy.getFCCutConfiguration())) {
            this.reset();
            myCutRoundDone = true;
            return true;
        } else {
            return false;
        }
    }

    double getReducedGradient(final int globalModelIndex) {
        if (this.isSolved() && this.getSolver() instanceof UpdatableSolver) {
            int indexInSolver = this.getIndexInSolver(globalModelIndex);
            if (indexInSolver >= 0) {
                return ((UpdatableSolver) this.getSolver()).getReducedGradient(indexInSolver);
            }
        }
        return 0.0;
    }

    boolean isCutRoundDone() {
        return myCutRoundDone;
    }

    /**
     * Whether this node's relaxation can absorb a branch-induced bound change in place (via
     * {@code update(variable)}) instead of being rebuilt from scratch.
     * <p>
     * True only for the linear/simplex relaxation: there {@code SimplexSolver.updateRange} genuinely applies
     * the change in place. A quadratic relaxation is solved by a convex solver — ADMM drifts when
     * warm-started across bound changes and the active-set path effectively rebuilds anyway — so those must
     * keep the historical, numerically-stable behaviour of rebuilding fresh on every branch
     * ({@link NodeKey#enforceBounds(NodeSolver, ModelStrategy)} forces a {@code reset()} for them, as the
     * original over-broad sign-change condition implicitly did). The model's structure is fixed for this
     * solver's lifetime, so the answer is cached.
     */
    boolean isInPlaceBoundUpdateSafe() {
        if (myInPlaceBoundUpdateSafe == null) {
            myInPlaceBoundUpdateSafe = Boolean.valueOf(!this.getModel().isAnyExpressionQuadratic());
        }
        return myInPlaceBoundUpdateSafe.booleanValue();
    }

}
